=== 8D-Productions/browscap/schema/divisions.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "division": {
      "type": "string"
    },
    "versions": {
      "type": "array",
      "items": {
        "anyOf": [
          { "type": "string" },
          { "type": "integer" }
        ]
      }
    },
    "sortIndex": {"type": "integer"},
    "lite": {
      "type": "boolean"
    },
    "standard": {
      "type": "boolean"
    },
    "userAgents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "userAgent": {"type": "string"},
          "browser": {"type": "string"},
          "platform": {"type": "string"},
          "engine": {"type": "string"},
          "device": {"type": "string"},
          "properties": {
            "type": "object",
            "properties": {
              "Parent": {"type": "string"},
              "Comment": {"type": "string"},
              "Version": {"type": "string"},
              "Browser_Modus": {"type": "string"},
              "Alpha": {"type": "boolean"},
              "Beta": {"type": "boolean"},
              "isFake": {"type": "boolean"},
              "isAnonymized": {"type": "boolean"},
              "isModified": {"type": "boolean"}
            },
            "required": [
              "Parent",
              "Comment"
            ]
          },
          "children": {
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        },
        "required": [
          "userAgent"
        ]
      }
    },
    "required": [
      "division",
      "sortIndex",
      "lite",
      "standard",
      "userAgents"
    ]
  }
}

=== 8D-Productions/browscap/resources/user-agents/browsers/openwave-mobile-browser/openwave-mobile-browser-7-2.json
{
  "division": "Openwave Mobile Browser #MAJORVER#.#MINORVER#",
  "versions": ["7.2"],
  "sortIndex": 8210,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Openwave Mobile Browser #MAJORVER#.#MINORVER#",
      "device": "general Mobile Phone",
      "platform": "JAVA",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Openwave Mobile Browser #MAJORVER#.#MINORVER#",
        "Browser": "Openwave Mobile Browser",
        "Browser_Type": "Browser",
        "Browser_Maker": "Myriad Group",
        "Version": "#MAJORVER#.#MINORVER#"
      },
      "children": [
        {
          "match": "#DEVICE#/*UP.Browser/#MAJORVER#.#MINORVER#*",
          "devices": {
            "MOT-VE538": "Motorola VE538",
            "SAGEM-VF526": "Sagem VF526",
            "SAGEM-VF540": "Sagem VF540"
          }
        },
        {
          "match": "Nokia* UP.Browser/#MAJORVER#.#MINORVER#*",
          "device": "general Mobile Phone (Nokia)"
        },
        {
          "match": "* UP.Browser/#MAJORVER#.#MINORVER#*"
        },
        {
          "match": "*UP.Browser/#MAJORVER#.#MINORVER#*"
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/apps/twitter-app.json
{
  "division": "Twitter App",
  "sortIndex": 1950,
  "lite": true,
  "userAgents": [
    {
      "userAgent": "Twitter App",
      "engine": "WebKit",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Twitter App",
        "Browser": "Twitter App",
        "Browser_Type": "Application",
        "Browser_Maker": "Twitter",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "isMobileDevice": "true",
        "CssVersion": "3",
        "Device_Type": "Mobile Phone",
        "Device_Pointing_Method": "touchscreen"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (iPhone#PLATFORM#) AppleWebKit\/* (KHTML, like Gecko) Mobile\/* Twitter for iPhone",
          "device": "iPhone",
          "platforms": [
            "iOS_A_7_1", "iOS_A_8_0", "iOS_A"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) AppleWebKit\/* (KHTML, like Gecko) Mobile\/* Twitter*",
          "device": "general Mobile Device (Apple)",
          "platforms": [
            "iOS_A_7_1", "iOS_A_8_0", "iOS_A"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/crawlers/general-crawlers/xml-sitemaps-generator.json
{
  "division": "XML Sitemaps Generator",
  "sortIndex": 170,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "XML Sitemaps Generator",
      "engine": "Gecko",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "XML Sitemaps Generator",
        "Browser": "XML Sitemaps Generator",
        "Browser_Maker": "XML Sitemaps",
        "Browser_Type": "Bot/Crawler",
        "Crawler": "true"
      },
      "children": [
        {
          "match": "XML Sitemaps Generator*",
          "engine": "unknown"
        },
        {
          "match": "Mozilla/5.0 (compatible; XML Sitemaps Generator; *) Gecko XML-Sitemaps/1.0*",
          "properties": {
            "Version": "1.0"
          }
        },
        {
          "match": "Mozilla/5.0 (compatible; XML Sitemaps Generator; *) Gecko XML-Sitemaps/*"
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/browsers/opera-neon/opera-neon-generic.json
{
  "division": "Opera Neon Generic",
  "sortIndex": 1044,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Opera Neon Generic",
      "browser": "opera neon",
      "engine": "Blink",
      "device": "Windows Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Opera Neon Generic"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*)*Chrome/*Safari/*MMS/*",
          "device": "Windows Desktop",
          "platforms": [
            "Win10_x64_B", "Win10_64_B", "Win10_32_B",
            "Win10_x64", "Win10_64", "Win10_32"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*)*Chrome/*Safari/*MMS/*",
          "device": "Macintosh",
          "platforms": [
            "OSX_10_12",
            "OSX"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/apps/tumblr-app.json
{
  "division": "Tumblr App #MAJORVER#.#MINORVER#",
  "versions": ["14.0"],
  "sortIndex": 1991,
  "lite": true,
  "userAgents": [
    {
      "userAgent": "Tumblr App #MAJORVER#.#MINORVER#",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Tumblr App #MAJORVER#.#MINORVER#",
        "Browser": "Tumblr App",
        "Browser_Type": "Application",
        "Browser_Maker": "Tumblr, Inc.",
        "Version": "#MAJORVER#.#MINORVER#",
        "MajorVer": "#MAJORVER#",
        "MinorVer": "#MINORVER#",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "isMobileDevice": "false",
        "isTablet": "false",
        "CssVersion": "3",
        "RenderingEngine_Name": "WebKit",
        "RenderingEngine_Maker": "Apple Inc",
        "RenderingEngine_Description": "For Google Chrome, iOS (including both mobile Safari, WebViews within third-party apps, and web clips), Safari, Arora, Midori, OmniWeb, Shiira, iCab since version 4, Web, SRWare Iron, Rekonq, and in Maxthon 3."
      },
      "children": [
        {
          "match": "Tumblr\/#MAJORVER#.#MINORVER#*"
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/crawlers/search-engines/stumble-upon.json
{
  "division": "StumbleUpon",
  "sortIndex": 10,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "StumbleUpon",
      "platform": "Windows",
      "device": "Windows Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "StumbleUpon",
        "Browser": "StumbleUpon",
        "Browser_Maker": "StumbleUpon, Inc.",
        "Browser_Type": "Bot/Crawler",
        "Crawler": "true"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) Gecko/* Mozilla/5.0 StumbleUpon/*",
          "engine": "Gecko",
          "platforms": [
            "WinXPa_32"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) Gecko/* Firefox/* StumbleUpon/*",
          "engine": "Gecko",
          "platforms": [
            "Win98"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#stumbleupon.com) Gecko/* Firefox/*",
          "engine": "Gecko",
          "platforms": [
            "Win7_32"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#stumbleupon.com) Chrome/* Safari/*",
          "engine": "Blink",
          "platforms": [
            "Win7_32"
          ]
        },
        {
          "match": "Mozilla/4.0 (compatible; MSIE ?.0; #PLATFORM#; StumbleUpon.com*",
          "engine": "Trident",
          "platforms": [
            "WinXPa_32"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/browsers/qt/qtwebengine-generic.json
{
  "division": "QtWebEngine Generic",
  "sortIndex": 1177,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "QtWebEngine Generic",
      "browser": "qtwebengine",
      "platform": "Windows",
      "engine": "Blink",
      "device": "Windows Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "QtWebEngine Generic"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) QtWebEngine/*Chrome/*Safari/*",
          "device": "Windows Desktop",
          "platforms": [
            "Win8_1_64", "Win8_1_32",
            "Win8_64", "Win8_32",
            "Win7_64", "Win7_32",
            "Vista_64", "Vista_32"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/apps/wordpress/word-press-app.json
{
  "division": "WordPress iPhone App",
  "sortIndex": 312,
  "lite": true,
  "userAgents": [
    {
      "userAgent": "WordPress iPhone App",
      "engine": "WebKit",
      "device": "general Mobile Device (Apple)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "WordPress iPhone App",
        "Browser": "WordPress iPhone App",
        "Browser_Type": "Application",
        "Browser_Maker": "WordPress.org",
        "Frames": "true",
        "Tables": "true"
      },
      "children": [
        {
          "match": "wp-iphone\/4.4 (#PLATFORM#, iPad) Mobile*",
          "properties": {
            "Version": "4.4",
            "MajorVer": "4",
            "MinorVer": "4"
          },
          "device": "iPad",
          "platforms": [
            "iOS_K_8_0", "iOS_K"
          ]
        },
        {
          "match": "wp-iphone\/* (#PLATFORM#, iPad) Mobile*",
          "device": "iPad",
          "platforms": [
            "iOS_K_8_0", "iOS_K"
          ]
        },
        {
          "match": "wp-iphone\/4.4 (#PLATFORM#) Mobile*",
          "properties": {
            "Version": "4.4",
            "MajorVer": "4",
            "MinorVer": "4"
          },
          "platforms": [
            "iOS_K_8_0", "iOS_K"
          ]
        },
        {
          "match": "wp-iphone\/* (#PLATFORM#) Mobile*",
          "platforms": [
            "iOS_K_8_0", "iOS_K"
          ]
        }
      ]
    }
  ]
}
