=== 8D-Productions/browscap/schema/divisions.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "division": {
      "type": "string"
    },
    "versions": {
      "type": "array",
      "items": {
        "anyOf": [
          { "type": "string" },
          { "type": "integer" }
        ]
      }
    },
    "sortIndex": {"type": "integer"},
    "lite": {
      "type": "boolean"
    },
    "standard": {
      "type": "boolean"
    },
    "userAgents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "userAgent": {"type": "string"},
          "browser": {"type": "string"},
          "platform": {"type": "string"},
          "engine": {"type": "string"},
          "device": {"type": "string"},
          "properties": {
            "type": "object",
            "properties": {
              "Parent": {"type": "string"},
              "Comment": {"type": "string"},
              "Version": {"type": "string"},
              "Browser_Modus": {"type": "string"},
              "Alpha": {"type": "boolean"},
              "Beta": {"type": "boolean"},
              "isFake": {"type": "boolean"},
              "isAnonymized": {"type": "boolean"},
              "isModified": {"type": "boolean"}
            },
            "required": [
              "Parent",
              "Comment"
            ]
          },
          "children": {
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        },
        "required": [
          "userAgent"
        ]
      }
    },
    "required": [
      "division",
      "sortIndex",
      "lite",
      "standard",
      "userAgents"
    ]
  }
}

=== 8D-Productions/browscap/resources/user-agents/email-clients/thunderbird/thunderbird-52-0-on.json
{
  "division": "Thunderbird #MAJORVER#.#MINORVER#",
  "versions": ["52.4", "52.3", "52.2", "52.1", 52],
  "sortIndex": 3084,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Thunderbird #MAJORVER#.#MINORVER#",
      "engine": "Gecko_Major_Dynamic",
      "device": "general Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Thunderbird #MAJORVER#.#MINORVER#",
        "Browser": "Thunderbird",
        "Browser_Maker": "Mozilla Foundation",
        "Browser_Type": "Email Client",
        "Version": "#MAJORVER#.#MINORVER#"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#)*Gecko*Thunderbird/#MAJORVER#.#MINORVER#*",
          "device": "Linux Desktop",
          "platforms": [
            "Linux_64", "Linux"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#)*Gecko*Thunderbird/#MAJORVER#.#MINORVER#*",
          "device": "Windows Desktop",
          "platforms": [
            "Win10_64_B", "Win10_32_B",
            "Win8_1_64", "Win8_1_32",
            "Win8_64", "Win8_32",
            "Win7_64", "Win7_32",
            "Vista_64", "Vista_32",
            "WinXPa_64", "WinXPa_32", "WinXPb_64", "WinXPb_32"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#)*Gecko*Thunderbird/#MAJORVER#.#MINORVER#*",
          "device": "Macintosh",
          "platforms": [
            "OSX_10_13", "OSX_10_12", "OSX_10_11", "OSX_10_10", "OSX_10_9",
            "OSX"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#)*Gecko*Thunderbird/#MAJORVER#.#MINORVER#*",
          "platforms": [
            "SunOS"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/feed-readers/akregator/akregator-generic.json
{
  "division": "akregator Generic",
  "sortIndex": 382,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "akregator Generic",
      "browser": "akregator",
      "engine": "KHTML_Dynamic",
      "platform": "Linux",
      "device": "Linux Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "akregator Generic"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (X11;) applewebkit* (*khtml*like*gecko*) akregator/* Safari/*"
        },
        {
          "match": "Akregator/*"
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/browsers/puffin/puffin-3-0.json
{
  "division": "Puffin #MAJORVER#.#MINORVER#",
  "versions": [3],
  "sortIndex": 1121,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Puffin #MAJORVER#.#MINORVER#",
      "engine": "Blink",
      "device": "general Mobile Phone (Touch)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Puffin #MAJORVER#.#MINORVER#",
        "Browser": "Puffin",
        "Version": "#MAJORVER#.#MINORVER#",
        "MajorVer": "#MAJORVER#",
        "MinorVer": "#MINORVER#",
        "Browser_Type": "Browser",
        "Browser_Maker": "CloudMosa Inc.",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "CssVersion": "2"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#LG-E730 Build/*) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*AP*",
          "device": "LG E730",
          "platforms": [
            "Android_4_0"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#THOT61 Build/*) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*AP*",
          "device": "Thornton Pickard THOT61",
          "platforms": [
            "Android_4_4"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*AP*",
          "platforms": [
            "Android_4_0", "Android_4_1", "Android_4_2", "Android_4_3", "Android_4_4", "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*AT*",
          "device": "general Tablet",
          "platforms": [
            "Android_4_0", "Android_4_1", "Android_4_2", "Android_4_3", "Android_4_4", "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (*Linux x86_64*) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*AP*",
          "platforms": [
            "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (*Linux x86_64*) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*AT*",
          "device": "general Tablet",
          "platforms": [
            "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (*Linux x86_64*) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*IP*",
          "device": "iPhone",
          "engine": "WebKit",
          "platforms": [
            "iOS"
          ]
        },
        {
          "match": "Mozilla/5.0 (*Linux x86_64*) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*IT*",
          "device": "iPad",
          "engine": "WebKit",
          "platforms": [
            "iOS"
          ]
        },
        {
          "match": "Mozilla/5.0 (*Linux x86_64*) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*I?*",
          "device": "general Mobile Device (Apple)",
          "engine": "WebKit",
          "platforms": [
            "iOS"
          ]
        },
        {
          "match": "Mozilla/5.0 (#DEVICE##PLATFORM#) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*I?*",
          "devices": {
            "iPhone": "iPhone",
            "iPod": "iPod Touch"
          },
          "engine": "WebKit",
          "platforms": [
            "iOS_A_7_1", "iOS_A_7_0",
            "iOS_A_6_1", "iOS_A_6_0",
            "iOS_A_5_1", "iOS_A_5_0",
            "iOS_A"
          ]
        },
        {
          "match": "Mozilla/5.0 (#DEVICE##PLATFORM#) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*I?*",
          "devices": {
            "iPad": "iPad"
          },
          "engine": "WebKit",
          "platforms": [
            "iOS_C_7_1", "iOS_C_7_0",
            "iOS_C_6_1", "iOS_C_6_0",
            "iOS_C_5_1", "iOS_C_5_0",
            "iOS_C"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) *Chrome/* Safari/* Puffin/#MAJORVER#*I?*",
          "device": "general Mobile Device (Apple)",
          "engine": "WebKit",
          "platforms": [
            "iOS_A",
            "iOS_C"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/browsers/chrome/chrome-28-to-36.json
{
  "division": "Chrome #MAJORVER#.#MINORVER#",
  "versions": [36, 35, 34, 33, 32, 31, 30, 29, 28],
  "sortIndex": 1147,
  "lite": false,
  "standard": false,
  "userAgents": [
    {
      "userAgent": "Chrome #MAJORVER#.#MINORVER#",
      "engine": "Blink",
      "device": "general Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Chrome #MAJORVER#.#MINORVER#",
        "Browser": "Chrome",
        "Browser_Maker": "Google Inc",
        "Browser_Type": "Browser",
        "Version": "#MAJORVER#.#MINORVER#"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#*Safari/*",
          "device": "Linux Desktop",
          "platforms": [
            "ChromeOS_x64", "ChromeOS",
            "Linux_64", "Linux"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Debian Chrome/#MAJORVER#.#MINORVER#*Safari/*",
          "device": "Linux Desktop",
          "platforms": [
            "Debian"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#*Safari/*",
          "device": "Windows Desktop",
          "platforms": [
            "WinXPa_64", "WinXPa_32", "WinXPb_64", "WinXPb_32",
            "Vista_64", "Vista_32",
            "Win7_64", "Win7_32",
            "Win8_64", "Win8_32",
            "Win8_1_64", "Win8_1_32",
            "Win10_64", "Win10_32", "Win10_64_B", "Win10_32_B"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#*Safari/*",
          "device": "Macintosh",
          "platforms": [
            "OSX_10_12", "OSX_10_11", "OSX_10_10", "OSX_10_9", "OSX_10_8", "OSX_10_7", "OSX_10_6"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#*Safari/*",
          "device": "general Desktop",
          "platforms": [
            "FreeBSD_64", "FreeBSD_64_2", "FreeBSD",
            "OpenBSD_64_3", "OpenBSD_64_2", "OpenBSD_64", "OpenBSD",
            "NetBSD"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#* anonymized by*",
          "properties": {
            "isAnonymized": "true"
          },
          "device": "Windows Desktop",
          "platforms": [
            "WinXPa_64", "WinXPa_32", "WinXPb_64", "WinXPb_32",
            "Vista_64", "Vista_32",
            "Win7_64", "Win7_32",
            "Win8_64", "Win8_32",
            "Win8_1_64", "Win8_1_32",
            "Win10_64", "Win10_32", "Win10_64_B", "Win10_32_B"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#*Anonymisiert durch*",
          "properties": {
            "isAnonymized": "true"
          },
          "device": "Windows Desktop",
          "platforms": [
            "WinXPa_64", "WinXPa_32", "WinXPb_64", "WinXPb_32",
            "Vista_64", "Vista_32",
            "Win7_64", "Win7_32",
            "Win8_64", "Win8_32",
            "Win8_1_64", "Win8_1_32",
            "Win10_64", "Win10_32", "Win10_64_B", "Win10_32_B"
          ]
        },
        {
          "match": "Mozilla/5.0 (Web0S; Linux/SmartTV) applewebkit* (*khtml*like*gecko*) QtWebEngine/* Chrome/#MAJORVER#.#MINORVER#* Safari/*LGE; 49UH668V*",
          "device": "LG 49UH668V",
          "platforms": [
            "webOS_30"
          ]
        },
        {
          "match": "Mozilla/5.0 (Web0S; Linux/SmartTV) applewebkit* (*khtml*like*gecko*) QtWebEngine/* Chrome/#MAJORVER#.#MINORVER#* Safari/*",
          "device": "general TV Device",
          "platforms": [
            "webOS_30"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit*(*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#* CrKey/*",
          "device": "Google Chromecast",
          "platforms": [
            "Chromecast_OS_ARM", "Chromecast_OS_64_ARM"
          ]
        },
        {
          "match": "Mozilla/5.0 (*CrKey arm*) applewebkit*(*khtml*like*gecko*) Chrome/#MAJORVER#.#MINORVER#*",
          "device": "Google Chromecast",
          "platforms": [
            "Chromecast_OS_ARM"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/browsers/baidu-browser/baidu-browser-hd-ios.json
{
  "division": "Baidu Browser HD #MAJORVER#.#MINORVER# for iOS",
  "versions": ["5.3", "5.2", "5.1", 5, 4, "3.5", "3.4", "3.3", "3.2", "3.1", 3, "2.6"],
  "sortIndex": 884,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Baidu Browser HD #MAJORVER#.#MINORVER# for iOS",
      "platform": "iOS",
      "engine": "WebKit",
      "device": "general Mobile Device (Apple)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Baidu Browser HD #MAJORVER#.#MINORVER#",
        "Browser": "Baidu Browser HD",
        "Browser_Type": "Browser",
        "Browser_Maker": "Baidu",
        "Version": "#MAJORVER#.#MINORVER#",
        "MajorVer": "#MAJORVER#",
        "MinorVer": "#MINORVER#",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "CssVersion": "3"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#DEVICE##PLATFORM#) applewebkit* (*khtml*like*gecko*) BaiduHD/#MAJORVER#.#MINORVER#* Mobile/* Safari/*",
          "devices": {
            "iPad": "iPad"
          },
          "platforms": [
            "iOS_A_10_3", "iOS_A_10_2", "iOS_A_10_1", "iOS_A_10_0",
            "iOS_A_9_3", "iOS_A_9_2", "iOS_A_9_1", "iOS_A_9_0",
            "iOS_A_8_4", "iOS_A_8_3", "iOS_A_8_2", "iOS_A_8_1", "iOS_A_8_0",
            "iOS_A_7_1", "iOS_A_7_0",
            "iOS_A_6_1", "iOS_A_6_0",
            "iOS_A",
            "iOS_C_10_3", "iOS_C_10_2", "iOS_C_10_1", "iOS_C_10_0",
            "iOS_C_9_3", "iOS_C_9_2", "iOS_C_9_1", "iOS_C_9_0",
            "iOS_C_8_4", "iOS_C_8_3", "iOS_C_8_2", "iOS_C_8_1", "iOS_C_8_0",
            "iOS_C_7_1", "iOS_C_7_0",
            "iOS_C_6_1", "iOS_C_6_0",
            "iOS_C"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/crawlers/general-crawlers/pagepeeker-screenshot-maker.json
{
  "division": "PagePeeker Screenshot Maker",
  "sortIndex": 2959,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "PagePeeker Screenshot Maker",
      "engine": "WebKit",
      "device": "Linux Desktop",
      "platform": "Linux",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "PagePeeker Screenshot Maker",
        "Browser": "PagePeeker Screenshot Maker",
        "Browser_Type": "Bot/Crawler",
        "Browser_Maker": "pagepeeker SRL",
        "Crawler": "true"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) domain.com Safari/*",
          "platforms": [
            "Linux_64", "Linux"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/crawlers/validation-checkers/validation-checkers.json
{
  "division": "Validation Checkers",
  "sortIndex": 390,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "HTML Validators",
      "browser": "html validators",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Validation Checkers"
      },
      "children": [
        {
          "match": "(HTML Validator http://www.searchengineworld.com/validator/)",
          "browser": "search engine world html validator",
          "properties": {
            "Browser": "Search Engine World HTML Validator"
          }
        },
        {
          "match": "FeedValidator/*",
          "browser": "feedvalidator",
          "properties": {
            "Browser": "FeedValidator"
          }
        },
        {
          "match": "Search Engine World Robots.txt Validator*",
          "browser": "search engine world robots.txt validator",
          "properties": {
            "Browser": "Search Engine World Robots.txt Validator"
          }
        },
        {
          "match": "Weblide/*",
          "browser": "weblide",
          "properties": {
            "Beta": "true"
          }
        },
        {
          "match": "WebmasterWorld StickyMail Server Header Checker*",
          "browser": "webmasterworld server header checker",
          "properties": {
            "Browser": "WebmasterWorld Server Header Checker"
          }
        },
        {
          "match": "WWWC/*",
          "browser": "wwwc",
          "properties": {
            "Browser": "WWWC"
          }
        },
        {
          "match": "WDG_Validator/1.6*",
          "browser": "wdg html validator",
          "properties": {
            "Version": "1.6"
          }
        },
        {
          "match": "WDG_Validator/*",
          "browser": "wdg html validator",
          "properties": {
            "Browser_Maker": "Web Design Group"
          }
        },
        {
          "match": "Mozilla/5.0 (compatible; Qualidator.com Bot 1.0*",
          "browser": "qualidator.com bot",
          "properties": {
            "Version": "1.0"
          }
        },
        {
          "match": "Mozilla/5.0 (compatible; Qualidator.com Bot*",
          "browser": "qualidator.com bot",
          "properties": {
            "Browser_Maker": "Qualidator.com"
          }
        },
        {
          "match": "CSE HTML Validator Online*",
          "browser": "cse html validator",
          "properties": {
            "Browser_Maker": "AI Internet Solutions LLC"
          }
        },
        {
          "match": "Mozilla/5.0 (compatible; Let's Encrypt validation server*",
          "browser": "let's encrypt validator",
          "properties": {
            "Browser_Maker": "Let's Encrypt"
          }
        },
        {
          "match": "Mozilla/5.0 (compatible; DomainSONOCrawler/*",
          "browser": "domainsono crawler",
          "properties": {
            "Browser_Maker": "DomainSONO"
          }
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/tests/fixtures/ua/ua-with-children-without-properties-array.json
{
  "division": "Division1",
  "versions": ["1.0"],
  "sortIndex": 200,
  "lite": true,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "UA1",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "UA1",
        "Browser": "UA1",
        "Version": "1.0",
        "MajorVer": "1",
        "MinorVer": "0"
      },
      "children": [
        {
          "match": "cde",
          "properties": "efg"
        }
      ]
    }
  ]
}
