=== 8D-Productions/browscap/schema/divisions.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "division": {
      "type": "string"
    },
    "versions": {
      "type": "array",
      "items": {
        "anyOf": [
          { "type": "string" },
          { "type": "integer" }
        ]
      }
    },
    "sortIndex": {"type": "integer"},
    "lite": {
      "type": "boolean"
    },
    "standard": {
      "type": "boolean"
    },
    "userAgents": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "userAgent": {"type": "string"},
          "browser": {"type": "string"},
          "platform": {"type": "string"},
          "engine": {"type": "string"},
          "device": {"type": "string"},
          "properties": {
            "type": "object",
            "properties": {
              "Parent": {"type": "string"},
              "Comment": {"type": "string"},
              "Version": {"type": "string"},
              "Browser_Modus": {"type": "string"},
              "Alpha": {"type": "boolean"},
              "Beta": {"type": "boolean"},
              "isFake": {"type": "boolean"},
              "isAnonymized": {"type": "boolean"},
              "isModified": {"type": "boolean"}
            },
            "required": [
              "Parent",
              "Comment"
            ]
          },
          "children": {
            "type": "array",
            "items": {
              "type": "object"
            }
          }
        },
        "required": [
          "userAgent"
        ]
      }
    },
    "required": [
      "division",
      "sortIndex",
      "lite",
      "standard",
      "userAgents"
    ]
  }
}

=== 8D-Productions/browscap/resources/user-agents/browsers/silk/silk-generic.json
{
  "division": "Silk Generic",
  "sortIndex": 1141,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Silk Generic",
      "platform": "Android",
      "engine": "Blink",
      "device": "Amazon Kindle",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Silk Generic",
        "Browser": "Silk",
        "Browser_Type": "Browser",
        "Browser_Maker": "Amazon.com, Inc.",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "CssVersion": "3"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Silk/* like Chrome/* Safari*",
          "engine": "Blink",
          "platforms": [
            "Android_5_1", "Android_5_0",
            "Android_4_4", "Android_4_3", "Android_4_2", "Android_4_1", "Android_4_0",
            "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (X11; Linux*) applewebkit* (*khtml*like*gecko*) Silk/* like Chrome/* Safari*",
          "engine": "Blink",
          "properties": {
            "Browser_Modus": "Desktop Mode"
          },
          "platforms": [
            "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Silk/* Safari*",
          "platforms": [
            "Android_4_0"
          ]
        },
        {
          "match": "Mozilla/5.0 (*Mac OS X 10*Silk/*) applewebkit* (*khtml*like*gecko*) Version/5.0 Safari*",
          "properties": {
            "Browser_Modus": "Desktop Mode"
          }
        },
        {
          "match": "Mozilla/5.0 (Linux*Android*Silk/*) applewebkit* (*khtml*like*gecko*) Chrome/* Safari/*"
        },
        {
          "match": "Mozilla/5.0 (Linux*Android*Silk/*) applewebkit* (*khtml*like*gecko*) Version/4.0 Mobile Safari*"
        },
        {
          "match": "Mozilla/5.0 (Linux*Android*Silk/*) applewebkit* (*khtml*like*gecko*) Version/4.0*Safari*",
          "device": "general Tablet"
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/browsers/dolfin/dolfin-2-2.json
{
  "division": "Dolfin #MAJORVER#.#MINORVER#",
  "versions": ["2.2"],
  "sortIndex": 1702,
  "lite": true,
  "userAgents": [
    {
      "userAgent": "Dolfin #MAJORVER#.#MINORVER#",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Dolfin #MAJORVER#.#MINORVER#",
        "Browser": "Dolfin",
        "Version": "#MAJORVER#.#MINORVER#",
        "MajorVer": "#MAJORVER#",
        "MinorVer": "#MINORVER#",
        "Platform": "Bada",
        "Platform_Description": "Samsung Bada",
        "Platform_Version": "1.2",
        "Win32": "false",
        "Device_Maker": "Samsung",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "isMobileDevice": "true",
        "CssVersion": "3",
        "RenderingEngine_Name": "WebKit",
        "RenderingEngine_Description": "For Google Chrome, iOS (including both mobile Safari, WebViews within third-party apps, and web clips), Safari, Arora, Midori, OmniWeb, Shiira, iCab since version 4, Web, SRWare Iron, Rekonq, and in Maxthon 3."
      },
      "children": [
        {
          "match": "Mozilla\/5.0 (SAMSUNG*SAMSUNG-GT-S#PLATFORM#)*AppleWebKit\/*(*KHTML, like Gecko*)*Dolfin\/#MAJORVER#.#MINORVER#*",
          "platforms": [
            "Bada_1_2"
          ]
        },
        {
          "match": "Samsung-* Dolphin/#MAJORVER#.#MINORVER#*"
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/crawlers/bittorrent-clients.json
{
  "division": "BitTorrent Client",
  "sortIndex": 260,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "BitTorrent Client",
      "browser": "bittorrent client",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "BitTorrent Client"
      },
      "children": [
        {
          "match": "Azureus*",
          "browser": "azureus",
          "properties": {
            "Browser": "Azureus"
          }
        },
        {
          "match": "BitComet/*",
          "browser": "bitcomet",
          "properties": {
            "Browser": "BitComet"
          }
        },
        {
          "match": "BitTornado/*",
          "browser": "bittornado",
          "properties": {
            "Browser": "BitTornado"
          }
        },
        {
          "match": "BitTorrent/*",
          "browser": "bittorrent",
          "properties": {
            "Browser": "BitTorrent"
          }
        },
        {
          "match": "BitTorrentMac/*",
          "browser": "bittorrentmac",
          "properties": {
            "Browser": "BitTorrentMac"
          }
        },
        {
          "match": "BTSP/*",
          "browser": "btsp",
          "properties": {
            "Browser": "BTSP"
          }
        },
        {
          "match": "Deluge*",
          "browser": "deluge",
          "properties": {
            "Browser": "Deluge"
          }
        },
        {
          "match": "FDM*",
          "browser": "fdm",
          "properties": {
            "Browser": "FDM"
          }
        },
        {
          "match": "KTorrent/*",
          "browser": "ktorrent",
          "properties": {
            "Browser": "KTorrent"
          }
        },
        {
          "match": "libtorrent/*",
          "browser": "libtorrent",
          "properties": {
            "Browser": "libtorrent"
          }
        },
        {
          "match": "MediaGet*",
          "browser": "mediaget",
          "properties": {
            "Browser": "MediaGet"
          }
        },
        {
          "match": "rtorrent/*",
          "browser": "rtorrent",
          "properties": {
            "Browser": "rtorrent"
          }
        },
        {
          "match": "Transmission/*",
          "browser": "transmission",
          "properties": {
            "Browser": "Transmission"
          }
        },
        {
          "match": "uTorrent/*",
          "browser": "utorrent",
          "properties": {
            "Browser": "uTorrent"
          }
        },
        {
          "match": "uTorrentMac/*",
          "browser": "utorrentmac",
          "properties": {
            "Browser": "uTorrentMac"
          }
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/crawlers/google/googlebot.json
{
  "division": "Googlebot",
  "sortIndex": 1148,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Googlebot",
      "browser": "google bot",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Googlebot"
      },
      "children": [
        {
          "match": "Googlebot/Test*"
        },
        {
          "match": "GoogleBot/*"
        },
        {
          "match": "googlebot-urlconsole",
          "browser": "googlebot-urlconsole",
          "properties": {
            "Browser": "googlebot-urlconsole"
          }
        },
        {
          "match": "Googlebot-Image*",
          "browser": "google image search",
          "properties": {
            "Browser": "Google Image Search"
          }
        },
        {
          "match": "Googlebot-News*",
          "browser": "googlebot-news",
          "properties": {
            "Browser": "Googlebot-News"
          }
        },
        {
          "match": "Googlebot-Video/1.0*",
          "browser": "googlebot-video",
          "properties": {
            "Version": "1.0"
          }
        },
        {
          "match": "Googlebot-Video*",
          "browser": "googlebot-video",
          "properties": {
            "Browser": "Googlebot-Video"
          }
        },
        {
          "match": "Mozilla/5.0 (en-us) applewebkit* (*khtml*like*gecko* Google PP Default) Chrome/* Safari/*"
        },
        {
          "match": "googlebot*"
        },
        {
          "match": "GOOG*"
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/apps/listia-app/lisria-app-generic.json
{
  "division": "Listia App Generic",
  "sortIndex": 1073,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Listia App Generic",
      "platform": "iOS",
      "engine": "WebKit",
      "device": "general Mobile Device (Apple)",
      "properties": {
        "Parent": "DefaultProperties",
        "Browser_Maker": "Listia Inc.",
        "Browser_Type": "Application",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "Crawler": "false",
        "Comment": "Listia App Generic",
        "Browser": "Listia App",
        "CssVersion": "3"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#DEVICE##PLATFORM#) applewebkit* (*khtml*like*gecko*) Mobile/* Listia/*",
          "devices": {
            "iPhone": "iPhone"
          },
          "platforms": [
            "iOS_A_10_3",
            "iOS_A"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Mobile/* Listia/*",
          "device": "general Mobile Device (Apple)",
          "platforms": [
            "iOS_A_10_3",
            "iOS_A"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/apps/microsoft/bing-search-app-generic.json
{
  "division": "Bing Search App Generic",
  "sortIndex": 482,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Bing Search App Generic for Android",
      "engine": "Blink",
      "device": "general Mobile Phone (Touch)",
      "platform": "Android",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Bing Search App Generic for Android",
        "Browser": "Bing Search App",
        "Browser_Type": "Application",
        "Browser_Maker": "Microsoft Corporation",
        "Crawler": "false"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Version/* Chrome/* Mobile Safari/* BingWeb/*",
          "platforms": [
            "Android_7_0",
            "Android_6_0",
            "Android_5_1", "Android_5_0",
            "Android_4_4", "Android_4_3", "Android_4_2", "Android_4_1", "Android_4_0",
            "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Chrome/* Mobile Safari/* BingWeb/*",
          "platforms": [
            "Android"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#) applewebkit* (*khtml*like*gecko*) Version/* Mobile Safari/* BingWeb/*",
          "engine": "WebKit",
          "platforms": [
            "Android_4_4", "Android_4_3", "Android_4_2", "Android_4_1", "Android_4_0",
            "Android_2_3",
            "Android"
          ]
        }
      ]
    },
    {
      "userAgent": "Bing Search App Generic for iOS",
      "platform": "iOS",
      "engine": "WebKit",
      "device": "general Mobile Device (Apple)",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Bing Search App Generic for iOS",
        "Browser": "Bing Search App",
        "Browser_Type": "Application",
        "Browser_Maker": "Microsoft Corporation",
        "Crawler": "false"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#DEVICE##PLATFORM#) applewebkit* (*khtml*like*gecko*) Mobile* BingWeb/*",
          "devices": {
            "iPhone": "iPhone"
          },
          "platforms": [
            "iOS_A_10_3", "iOS_A_10_2",
            "iOS_A_8_4",
            "iOS_A_7_0",
            "iOS_A"
          ]
        },
        {
          "match": "Mozilla/5.0 (#DEVICE##PLATFORM#) applewebkit* (*khtml*like*gecko*) Version/* Mobile* BingWeb/*",
          "devices": {
            "iPhone": "iPhone"
          },
          "platforms": [
            "iOS_A_10_3", "iOS_A_10_2",
            "iOS_A"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/email-clients/thunderbird/thunderbird-1-0-to-2-0.json
{
  "division": "Thunderbird #MAJORVER#.#MINORVER#",
  "versions": [2, "1.5", 1],
  "sortIndex": 3086,
  "lite": false,
  "standard": true,
  "userAgents": [
    {
      "userAgent": "Thunderbird #MAJORVER#.#MINORVER#",
      "engine": "Gecko_1",
      "device": "general Desktop",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Thunderbird #MAJORVER#.#MINORVER#",
        "Browser": "Thunderbird",
        "Browser_Maker": "Mozilla Foundation",
        "Browser_Type": "Email Client",
        "Version": "#MAJORVER#.#MINORVER#",
        "MajorVer": "#MAJORVER#",
        "MinorVer": "#MINORVER#",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "CssVersion": "2"
      },
      "children": [
        {
          "match": "Mozilla/5.0 (#PLATFORM#)*Gecko*Thunderbird/#MAJORVER#.#MINORVER#*",
          "device": "Linux Desktop",
          "platforms": [
            "Linux"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#)*Gecko*Thunderbird/#MAJORVER#.#MINORVER#*",
          "device": "Windows Desktop",
          "platforms": [
            "Vista_32",
            "WinXPa_32", "WinXPb_32",
            "Win2000", "NT4",
            "Win98", "WinME"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#)*Gecko*Thunderbird/#MAJORVER#.#MINORVER#*",
          "device": "Macintosh",
          "platforms": [
            "OSX_10_4", "OSX_10_3",
            "OSX"
          ]
        },
        {
          "match": "Mozilla/5.0 (#PLATFORM#)*Gecko*Thunderbird/#MAJORVER#.#MINORVER#*",
          "platforms": [
            "SunOS"
          ]
        }
      ]
    }
  ]
}

=== 8D-Productions/browscap/resources/user-agents/browsers/opera/opera-11-60.json
{
  "division": "Opera #MAJORVER#.#MINORVER#",
  "versions": ["11.60"],
  "sortIndex": 2820,
  "lite": true,
  "userAgents": [
    {
      "userAgent": "Opera #MAJORVER#.#MINORVER#",
      "properties": {
        "Parent": "DefaultProperties",
        "Comment": "Opera #MAJORVER#.#MINORVER#",
        "Browser": "Opera",
        "Version": "#MAJORVER#.#MINORVER#",
        "MajorVer": "#MAJORVER#",
        "MinorVer": "#MINORVER#",
        "Win32": "true",
        "Frames": "true",
        "IFrames": "true",
        "Tables": "true",
        "Cookies": "true",
        "JavaScript": "true",
        "JavaApplets": "true",
        "CssVersion": "3",
        "RenderingEngine_Name": "Presto",
        "RenderingEngine_Version": "2.10",
        "RenderingEngine_Description": "For Opera 7 and above, Macromedia Dreamweaver MX and MX 2004 (Mac), and Adobe Creative Suite 2."
      },
      "children": [
        {
          "match": "Mozilla\/?.*(#PLATFORM#)*Opera?#MAJORVER#.#MINORVER#*",
          "platforms": [
            "FreeBSD", "Linux", "OSX", "SunOS", "Win2000_2",
            "WinME", "Win95_2", "Win98_2", "WinME_2", "NT4", "Win2000",
            "WinXPa_32", "WinXPb_32", "Vista_32", "Win7_32"
          ]
        },
        {
          "match": "Mozilla\/?.*(*Opera?#MAJORVER#.#MINORVER##PLATFORM#)*",
          "platforms": [
            "FreeBSD", "Linux", "OSX", "SunOS", "Win2000_2",
            "WinME", "Win95_2", "Win98_2", "WinME_2", "NT4", "Win2000",
            "WinXPa_32", "WinXPb_32", "Vista_32", "Win7_32"
          ]
        },
        {
          "match": "Opera\/#MAJORVER#.#MINORVER#*(#PLATFORM#)*",
          "platforms": [
            "FreeBSD", "Linux", "OSX", "SunOS", "Win2000_2",
            "WinME", "Win95_2", "Win98_2", "WinME_2", "NT4", "Win2000",
            "WinXPa_32", "WinXPb_32", "Vista_32", "Win7_32"
          ]
        },
        {
          "match": "Opera\/9.80*(#PLATFORM#)*Version\/#MAJORVER#.#MINORVER#*",
          "platforms": [
            "FreeBSD", "Linux", "OSX", "SunOS", "Win2000_2",
            "WinME", "Win95_2", "Win98_2", "WinME_2", "NT4", "Win2000",
            "WinXPa_32", "WinXPb_32", "Vista_32", "Win7_32"
          ]
        }
      ]
    }
  ]
}
